### ISSUE TITLE
CloudflakeChallengeError

### ISSUE THREAD

**Issue by LeeTuah** [DarkCat09/python-aternos#71] opened 2023-03-16 17:23 UTC
This is the output on running the from_credentials() function in the Client class:

cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

**Comment by DarkCat09** [comment] 2023-03-17 03:12
Duplicate of #52

**Comment by DarkCat09** [comment] 2023-03-17 03:15
@LeeTuah, you need an API key on paid services like 2captcha for automatic captcha solving.  
See #52 for more information.

**Closed by DarkCat09** 2023-03-17 03:15 UTC
Labels: duplicate, cloudflare
