### ISSUE TITLE
Dont use this you will get Banned!

### ISSUE THREAD

**Issue by BluePlattypus** [DarkCat09/python-aternos#46] opened 2022-08-07 11:15 UTC
![image](https://user-images.githubusercontent.com/97361820/183287932-71e535f4-ff32-4231-b627-e4f2f632b6bc.png)

**Comment by BluePlattypus** [comment] 2022-08-07 15:05
I Just found out why, if you host this on repl.it aternos will recognize that the request is comming from a data center and will ban you. But can the Owner of this repo pls put this at the top of the readme pls

**Comment by didotb** [comment] 2022-08-07 17:14
> I Just found out why, if you host this on repl.it aternos will recognize that the request is comming from a data center and will ban you. But can the Owner of this repo pls put this at the top of the readme pls

Unfortunately that's not the reason why,
Read their TOS. You should've known that automating means they can't get money off of you from ads they place on their site and is therefore not allowed by them.

Doesn't matter if it's form a data center or a computer you own.

**Comment by BluePlattypus** [comment] 2022-08-08 07:11
ahh shit any way to bypass this?

**Comment by BluePlattypus** [comment] 2022-08-08 07:11
i can maybe try to look in the code

**Comment by DarkCat09** [comment] 2022-08-08 08:06
Duplicate of #16

**Comment by DarkCat09** [comment] 2022-08-08 08:08
@BluePlattypus, this can't be bypassed until we haven't source code of Aternos backend and tools for detecting automated access.

**Comment by DarkCat09** [comment] 2022-08-08 08:11
When you register on aternos.org, you must read Terms of Service.  
One of its paragraphs says that users shouldn't use parsers, etc. for [these reasons](https://github.com/DarkCat09/python-aternos/issues/46#issuecomment-1207449048).

**Comment by DarkCat09** [comment] 2022-08-08 08:13
Use `save_session` and `restore_session` to reduce count of API requests.  
This **may** help.

**Closed** 2022-08-08 08:12 UTC
Labels: duplicate
