### ISSUE TITLE
Aternos detects using this

### ISSUE THREAD

**Issue by pythoncat1** [DarkCat09/python-aternos#106] opened 2023-11-22 16:34 UTC
<img width="960" alt="image" src="https://github.com/DarkCat09/python-aternos/assets/119687855/fc9a861c-8a65-4c88-a5e0-ab00280f2a17">

**Comment by pythoncat1** [comment] 2023-11-27 17:22
@DarkCat09 any idea of what code mightve caused detection?

**Comment by DarkCat09** [comment] 2023-11-27 17:25
Duplicate of #85

**Closed** 2023-11-27 17:25 UTC
Labels: duplicate
