### ISSUE TITLE
list_servers() not working

### ISSUE THREAD

**Issue by Trololololol12** [DarkCat09/python-aternos#48] opened 2022-08-10 23:54 UTC
I am trying to use this api, but aternos.list_servers() returns an empty list. Any ideas why?

**Comment by didotb** [comment] 2022-08-10 23:57
Duplicate of #28

**Comment by Trololololol12** [comment] 2022-08-11 00:06
I only have one server on aternos, so it's something different

**Comment by didotb** [comment] 2022-08-11 00:09
> I only have one server on aternos, so it's something different

are using version 1.1.1?

**Comment by Trololololol12** [comment] 2022-08-11 00:11
Yeah

**Comment by Trololololol12** [comment] 2022-08-11 00:15
Also quick question I have the same problem as shown in #45 but I'm not sure how to bypass Cloudflare

**Comment by didotb** [comment] 2022-08-11 00:16
Please perform this specific comment https://github.com/DarkCat09/python-aternos/issues/30#issuecomment-1168213298
and send the console log here

**Comment by Trololololol12** [comment] 2022-08-11 00:19
DEBUG:root:Requesting(GET)https://aternos.org/go/
DEBUG:root:headers={}
DEBUG:root:params={}
DEBUG:root:data={}
DEBUG:root:req-cookies={'ATERNOS_SESSION': ''}
DEBUG:root:session-cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aternos.org:443
DEBUG:urllib3.connectionpool:https://aternos.org:443 "GET /go/ HTTP/1.1" 403 None
DEBUG:root:AternosConnect received: <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a mome
INFO:root:GET completed with 403 status
Traceback (most recent call last):
  File "C:\Users\boris\Downloads\pog.txt", line 5, in <module>
    aternos = Client.from_credentials('MyUsername', "MyPassword")
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atclient.py", line 86, in from_credentials
    return cls.from_hashed(username, md5)
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atclient.py", line 52, in from_hashed
    atconn.parse_token()
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atconnect.py", line 46, in parse_token
    loginpage = self.request_cloudflare(
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atconnect.py", line 263, in request_cloudflare
    req.raise_for_status()
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://aternos.org/go/

C:\Users\boris\Downloads>python pog.txt
DEBUG:root:Requesting(GET)https://aternos.org/go/
DEBUG:root:headers={}
DEBUG:root:params={}
DEBUG:root:data={}
DEBUG:root:req-cookies={'ATERNOS_SESSION': ''}
DEBUG:root:session-cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aternos.org:443
DEBUG:urllib3.connectionpool:https://aternos.org:443 "GET /go/ HTTP/1.1" 403 None
DEBUG:root:AternosConnect received: <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a mome
INFO:root:GET completed with 403 status
Traceback (most recent call last):
  File "C:\Users\boris\Downloads\pog.txt", line 5, in <module>
    aternos = Client.from_credentials('MyUsername', "MyPassword")
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atclient.py", line 86, in from_credentials
    return cls.from_hashed(username, md5)
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atclient.py", line 52, in from_hashed
    atconn.parse_token()
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atconnect.py", line 46, in parse_token
    loginpage = self.request_cloudflare(
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\python_aternos\atconnect.py", line 263, in request_cloudflare
    req.raise_for_status()
  File "C:\Users\boris\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://aternos.org/go/

C:\Users\boris\Downloads>python pog.txt
DEBUG:root:Requesting(GET)https://aternos.org/go/
DEBUG:root:headers={}
DEBUG:root:params={}
DEBUG:root:data={}
DEBUG:root:req-cookies={'ATERNOS_SESSION': ''}
DEBUG:root:session-cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aternos.org:443
DEBUG:urllib3.connectionpool:https://aternos.org:443 "GET /go/ HTTP/1.1" 200 None
DEBUG:root:AternosConnect received: <!DOCTYPE html>
<html>
    <head>
        <base href="/panel/"/>

INFO:root:GET completed with 200 status
DEBUG:root:Requesting(POST)https://aternos.org/panel/ajax/account/login.php
DEBUG:root:headers={'X-Requested-With': 'XMLHttpRequest'}
DEBUG:root:params={'TOKEN': 'fnLwr2zVwh9ZcclTdNBX', 'SEC': '1gyyupgai9800000:2kpgr869kxn00000'}
DEBUG:root:data={'user': 'WAA13', 'password': 'e9c0bf373aa2f726136a28a2cc59b1fb'}
DEBUG:root:req-cookies={'ATERNOS_SESSION': ''}
DEBUG:root:session-cookies=<RequestsCookieJar[<Cookie ATERNOS_LANGUAGE=en for aternos.org/>, <Cookie ATERNOS_SEC_1gyyupgai9800000=2kpgr869kxn00000 for aternos.org/>]>
DEBUG:urllib3.connectionpool:https://aternos.org:443 "POST /panel/ajax/account/login.php?TOKEN=fnLwr2zVwh9ZcclTdNBX&SEC=1gyyupgai9800000%3A2kpgr869kxn00000 HTTP/1.1" 200 None
DEBUG:root:AternosConnect received: {"success":true,"error":null,"message":null,"show2FA":false}
INFO:root:POST completed with 200 status
DEBUG:root:Requesting(GET)https://aternos.org/servers/
DEBUG:root:headers={}
DEBUG:root:params={}
DEBUG:root:data={}
DEBUG:root:req-cookies={'ATERNOS_SESSION': 'opXnnrXNojOyzqj8ufOMRho0EmFDp0ZC21JSkHNANKYjpDsa7TMr5JXTZpJhiJzn7XU8pnYY2WLwNN5dQurrCcBS50HJyYa7pXuK'}
DEBUG:root:session-cookies=<RequestsCookieJar[<Cookie ATERNOS_LANGUAGE=en for aternos.org/>, <Cookie ATERNOS_SEC_1gyyupgai9800000=2kpgr869kxn00000 for aternos.org/>]>
DEBUG:urllib3.connectionpool:https://aternos.org:443 "GET /servers/ HTTP/1.1" 200 None
DEBUG:root:AternosConnect received: <!DOCTYPE html>
<html class="account-layout">
<head>
    <meta ch
INFO:root:GET completed with 200 status
[]
Traceback (most recent call last):
  File "C:\Users\boris\Downloads\pog.txt", line 10, in <module>
    s = srvs[0]
IndexError: list index out of range

**Comment by Trololololol12** [comment] 2022-08-11 00:20
I'm seeing 403's at the top and then 200's at the botttom which is confusing me

**Comment by Trololololol12** [comment] 2022-08-11 00:21
Also  I changed my actual username and password to "MyUsername" and "MyPassword" in the comment with the log

**Comment by Trololololol12** [comment] 2022-08-11 00:22
I just tried the "world35g" login and it works for me

**Comment by didotb** [comment] 2022-08-11 00:25
Seems like the cloudflare problem again.
There doesn't seem to be any fix to it yet

**Comment by Trololololol12** [comment] 2022-08-11 00:27
:(

**Comment by DarkCat09** [comment] 2022-08-11 10:58
@Trololololol12, when you ran your script the fist time and got 403 error, that was a Cloudflare bypassing issue.  
But empty list is not related to the protection.

I'll check xpath expression.  
It might not work with one server, it was tested only with multiple servers.

**Comment by DarkCat09** [comment] 2022-08-19 06:27
The issue was reproduced on my test account `world35g` and confirmed.

**Comment by DarkCat09** [comment] 2022-08-19 06:39
Sorry, I just forgot to update local git repository.  
This bug was fixed by #43 a long time ago.  
I'll write a comment here when `v1.1.2` is released.

**Closed by DarkCat09** 2022-08-19 06:40 UTC
Labels: bug
